#!/usr/bin/env python3
"""Write the IRENA-30 ZREFL DONJON consumer decks.

Two decks are produced:

- ``irena30_zrefl_sn8_<stamp>.x2m``  — NCR: + SNT: SN8 transport (primary
  comparison; mirrors the geometry/solver options of the accepted IRENA
  DONJON SN decks, with one mixture per hex position).
- ``irena30_zrefl_mcfd_<stamp>.x2m`` — NCR: + TRIVAC MCFD 1 diffusion
  (coarse-mesh diagnostic; MCFD requires unsplit hexes).

Hex ordering: the multicompo mixtures are written in (ring, position) order,
which is the DRAGON HEXZ numbering used by the reference IRENA decks, so the
GEO: MIX list is simply 1..91.
"""

from __future__ import annotations

import argparse
from pathlib import Path

SIDE_CM = "10.1036"
N_HEX = 91


def mix_use_lines() -> str:
    return "\n".join(f"  MIX {i} USE ENDMIX" for i in range(1, N_HEX + 1))


def mix_number_lines() -> str:
    return "\n".join(
        "  " + " ".join(str(i) for i in range(start, min(start + 10, N_HEX + 1)))
        for start in range(1, N_HEX + 1, 10)
    )


HEADER = """*----
*  IRENA-30 91-hex 2D ARI ZREFL: converted L_MULTICOMPO -> NCR -> {solver}.
*  Generated by openmc2donjon examples/irena30_zrefl_hex.
*  Reference: paired OpenMC-MG run (same 33g macrolib, same geometry).
*----
"""

SN8_TEMPLATE = HEADER + """MODULE GEO: NCR: SNT: ASM: FLU: EDI: GREP: END: ;
LINKED_LIST CPO MACRO GEOM TRACK SYSTEM FLUX EDIRES ;
REAL keff ;
SEQ_ASCII CPO_ASC :: FILE '{mco}' ;
SEQ_ASCII EDI_ASC :: FILE '{edi}' ;

CPO := CPO_ASC ;
MACRO := NCR: CPO :: EDIT 1 MACRO NMIX 91
  COMPO CPO CPO
{mix_use}
;

GEOM := GEO: :: HEXZ 91 1 EDIT 0
  Z- REFL Z+ REFL  HBC COMPLETE VOID
  SIDE {side}  SPLITL 2
  MESHZ 0.0 10.0
  MIX
{mix_numbers}
;

TRACK := SNT: GEOM :: EDIT 0 DIAM 1 SN 8 SCAT 2 ;
SYSTEM := ASM: MACRO TRACK :: ARM ;
FLUX := FLU: SYSTEM MACRO TRACK :: EDIT 1 TYPE K EXTE 500 1E-05 ;

EDIRES := EDI: MACRO TRACK FLUX :: EDIT 2 MERG MIX COND SAVE ;
EDI_ASC := EDIRES ;

GREP: FLUX :: GETVAL 'K-EFFECTIVE' 1 >>keff<< ;
ECHO 'OPENMC2DONJON IRENA30 ZREFL NCR SN8 K-EFFECTIVE' keff ;
END: ;
"""

MCFD_TEMPLATE = HEADER + """MODULE GEO: NCR: TRIVAT: TRIVAA: FLUD: GREP: END: ;
LINKED_LIST CPO MACRO GEOM TRACK SYS FLUX ;
REAL keff ;
SEQ_ASCII CPO_ASC :: FILE '{mco}' ;

CPO := CPO_ASC ;
MACRO := NCR: CPO :: EDIT 1 MACRO NMIX 91
  COMPO CPO CPO
{mix_use}
;

GEOM := GEO: :: HEXZ 91 1 EDIT 0
  Z- REFL Z+ REFL  HBC COMPLETE VOID
  SIDE {side}
  MESHZ 0.0 10.0
  MIX
{mix_numbers}
;

TRACK := TRIVAT: GEOM ::
  TITLE 'IRENA30 ZREFL NCR MCFD diffusion'
  EDIT 1 MAXR 20000 MCFD 1 ;
SYS := TRIVAA: MACRO TRACK :: EDIT 0 ;
FLUX := FLUD: SYS TRACK :: EDIT 1 ACCE 3 3 EXTE 1000 1E-05 ADI 6 ;
GREP: FLUX :: GETVAL 'K-EFFECTIVE ' 1 >>keff<< ;
ECHO 'OPENMC2DONJON IRENA30 ZREFL NCR MCFD DIFFUSION K-EFFECTIVE' keff ;
END: ;
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mco", type=Path, required=True,
                        help="staged multicompo ASCII (short path, <72 chars)")
    parser.add_argument("--edi", type=Path, required=True,
                        help="L_EDIT ASCII dump target (short path, <72 chars)")
    parser.add_argument("--deck-dir", type=Path, required=True)
    parser.add_argument("--stamp", required=True)
    args = parser.parse_args()

    for path in (args.mco, args.edi):
        if len(str(path)) > 72:
            raise SystemExit(f"path exceeds DONJON's 72-character limit: {path}")

    args.deck_dir.mkdir(parents=True, exist_ok=True)
    common = {
        "mco": str(args.mco),
        "side": SIDE_CM,
        "mix_use": mix_use_lines(),
        "mix_numbers": mix_number_lines(),
    }
    sn8 = args.deck_dir / f"irena30_zrefl_sn8_{args.stamp}.x2m"
    mcfd = args.deck_dir / f"irena30_zrefl_mcfd_{args.stamp}.x2m"
    sn8.write_text(SN8_TEMPLATE.format(solver="SNT SN8", edi=str(args.edi), **common))
    mcfd.write_text(MCFD_TEMPLATE.format(solver="TRIVAC MCFD diffusion", **common))
    print(f"wrote {sn8}")
    print(f"wrote {mcfd}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
