#!/usr/bin/env python3
"""Write the IRENA-30 Stage 3 DONJON SN8 consumer deck.

Adapted from ``examples/irena30_zrefl_hex/write_donjon_decks.py``: one NCR +
SNT SN8 transport deck per staged multicompo (uncorrected or SPH-corrected),
mirroring the geometry/solver options of the accepted IRENA DONJON SN decks
(HEXZ 91, SIDE 10.1036, SPLITL 2, SN 8 SCAT 2, one mixture per hex
position).

Hex ordering: the multicompo mixtures are written in (ring, position)
order, which is the DRAGON HEXZ numbering used by the reference IRENA
decks, so the GEO: MIX list is simply 1..91.
"""

from __future__ import annotations

import argparse
from pathlib import Path

SIDE_CM = "10.1036"
N_HEX = 91
# CLE-2000's effective SEQ_ASCII limit includes internal bookkeeping beyond
# the visible filename on this DONJON build.  A 70-character path failed even
# though the nominal 72-character field accepted it; keep a measured margin.
MAX_SEQ_ASCII_PATH = 64


def mix_use_lines() -> str:
    return "\n".join(f"  MIX {i} USE ENDMIX" for i in range(1, N_HEX + 1))


def mix_number_lines() -> str:
    return "\n".join(
        "  " + " ".join(str(i) for i in range(start, min(start + 10, N_HEX + 1)))
        for start in range(1, N_HEX + 1, 10)
    )


SN8_TEMPLATE = """*----
*  IRENA-30 91-hex 2D ARI ZREFL Stage 3 ({tag}): L_MULTICOMPO -> NCR -> SNT SN8.
*  Generated by openmc2donjon examples/irena30_sph_stage3_fullcore.
*  Reference: OpenMC fine full core and assembly-homogenized MG full core.
*----
MODULE GEO: NCR: SNT: ASM: FLU: EDI: GREP: END: ;
LINKED_LIST CPO MACRO GEOM TRACK SYSTEM FLUX EDIRES ;
REAL keff ;
SEQ_ASCII CPO_ASC :: FILE '{mco}' ;
SEQ_ASCII EDI_ASC :: FILE '{edi}' ;

CPO := CPO_ASC ;
MACRO := NCR: CPO :: EDIT 1 MACRO NMIX 91
  COMPO CPO CPO
{mix_use}
;

GEOM := GEO: :: HEXZ 91 1 EDIT 0
  Z- REFL Z+ REFL  HBC COMPLETE VOID
  SIDE {side}  SPLITL 2
  MESHZ 0.0 10.0
  MIX
{mix_numbers}
;

TRACK := SNT: GEOM :: EDIT 0 DIAM 1 SN 8 SCAT 2 ;
SYSTEM := ASM: MACRO TRACK :: ARM ;
FLUX := FLU: SYSTEM MACRO TRACK :: EDIT 1 TYPE K EXTE 500 1E-05 ;

EDIRES := EDI: MACRO TRACK FLUX :: EDIT 2 MERG MIX COND SAVE ;
EDI_ASC := EDIRES ;

GREP: FLUX :: GETVAL 'K-EFFECTIVE' 1 >>keff<< ;
ECHO 'OPENMC2DONJON IRENA30 STAGE3 SN8 K-EFFECTIVE' keff ;
END: ;
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--mco",
        type=Path,
        required=True,
        help=f"staged multicompo ASCII (short path, <={MAX_SEQ_ASCII_PATH} chars)",
    )
    parser.add_argument(
        "--edi",
        type=Path,
        required=True,
        help=f"L_EDIT ASCII dump target (short path, <={MAX_SEQ_ASCII_PATH} chars)",
    )
    parser.add_argument("--deck-dir", type=Path, required=True)
    parser.add_argument("--stamp", required=True)
    parser.add_argument("--tag", required=True,
                        help="deck flavour, e.g. uncorr or sphcorr")
    args = parser.parse_args()

    for path in (args.mco, args.edi):
        if len(str(path)) > MAX_SEQ_ASCII_PATH:
            raise SystemExit(
                "path exceeds the conservative DONJON SEQ_ASCII limit "
                f"({MAX_SEQ_ASCII_PATH} characters): {path}"
            )

    args.deck_dir.mkdir(parents=True, exist_ok=True)
    deck = args.deck_dir / f"irena30_stage3_sn8_{args.tag}_{args.stamp}.x2m"
    deck.write_text(
        SN8_TEMPLATE.format(
            tag=args.tag,
            mco=str(args.mco),
            edi=str(args.edi),
            side=SIDE_CM,
            mix_use=mix_use_lines(),
            mix_numbers=mix_number_lines(),
        )
    )
    print(f"wrote {deck}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
