"""Strict full-core :math:`D_3` symmetry orbits for the IRENA-30 example.

These 21 records describe *global full-core positions*.  They are not the 13
local center-and-neighbor signatures in :mod:`topology`.  A local signature
can merge multiple global orbits which have the same immediate neighborhood
but occupy different symmetry-inequivalent positions in the full core.  Such
a merge is useful for constructing local models, but it is not a valid reason
by itself to tie full-core SPH factors.

For ring ``r > 0``, IRENA numbers the ``6*r`` positions consecutively.  The
full-core :math:`D_3` action used here is generated by

* the 120-degree rotation ``p -> p + 2*r``; and
* the reflection ``p -> -p``.

Consequently, an orbit is identified by the canonical residue
``min(p mod 2*r, -p mod 2*r)`` in ``0..r``.  Stable orbit numbers are assigned
first by ring and then by this canonical residue.  Orbit 1 is the center;
rings 1 through 5 then contribute 2, 3, 4, 5, and 6 orbits respectively.
This module is benchmark data and deliberately has no dependency on an
external IRENA checkout.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Iterable


RING_POSITION_COUNTS = (1, 6, 12, 18, 24, 30)
MATERIALS = frozenset({"INT", "EXT", "CSD", "DSDF", "PNL"})


def material_for_position(ring: int, position: int) -> str:
    """Return the declared IRENA material at one full-core position."""

    _validate_position(ring, position)
    if ring == 0:
        return "INT"
    if ring == 1:
        return "DSDF" if position % 2 == 0 else "INT"
    if ring == 2:
        return "INT"
    if ring == 3:
        return "CSD" if position % 3 == 0 else "INT"
    if ring == 4:
        return "EXT"
    return "PNL"


def canonical_residue(ring: int, position: int) -> int:
    """Return the ``0..ring`` representative of a full-core D3 orbit."""

    _validate_position(ring, position)
    if ring == 0:
        return 0
    period = 2 * ring
    residue = position % period
    return min(residue, (-residue) % period)


def generated_members(ring: int, representative: int) -> tuple[int, ...]:
    """Generate sorted ring positions from the D3 rotation/reflection formula."""

    if ring == 0:
        if representative != 0:
            raise ValueError("the center orbit must use representative 0")
        return (0,)
    if not 1 <= ring < len(RING_POSITION_COUNTS):
        raise ValueError(f"invalid IRENA ring: {ring}")
    if not 0 <= representative <= ring:
        raise ValueError(
            f"ring {ring} orbit representative must be in 0..{ring}"
        )

    period = 2 * ring
    reflected_residues = {representative, (-representative) % period}
    return tuple(
        sorted(
            residue + rotation * period
            for residue in reflected_residues
            for rotation in range(3)
        )
    )


@dataclass(frozen=True)
class GlobalD3Orbit:
    """One global IRENA full-core symmetry orbit."""

    number: int
    ring: int
    representative: int
    material: str
    positions: tuple[int, ...]

    def __post_init__(self) -> None:
        expected = generated_members(self.ring, self.representative)
        if self.number < 1:
            raise ValueError("orbit numbers start at 1")
        if self.material not in MATERIALS:
            raise ValueError(f"unknown IRENA material: {self.material!r}")
        if self.positions != expected:
            raise ValueError(
                f"orbit {self.number} members {self.positions} do not match {expected}"
            )
        labels = {material_for_position(self.ring, position) for position in expected}
        if labels != {self.material}:
            raise ValueError(
                f"orbit {self.number} crosses material labels: {sorted(labels)}"
            )

    @property
    def id(self) -> str:
        """Stable, zero-padded human-readable orbit id."""

        return f"O{self.number:02d}"

    @property
    def members(self) -> tuple[tuple[int, int], ...]:
        """Return ``(ring, position)`` members."""

        return tuple((self.ring, position) for position in self.positions)

    @property
    def multiplicity(self) -> int:
        """Number of physical hexagons represented by this orbit."""

        return len(self.positions)


def _validate_position(ring: int, position: int) -> None:
    if not 0 <= ring < len(RING_POSITION_COUNTS):
        raise ValueError(f"invalid IRENA ring: {ring}")
    count = RING_POSITION_COUNTS[ring]
    if not 0 <= position < count:
        raise ValueError(
            f"position {position} is outside ring {ring} (expected 0..{count - 1})"
        )


def _build_orbits() -> tuple[GlobalD3Orbit, ...]:
    definitions: list[GlobalD3Orbit] = []
    number = 1
    for ring in range(len(RING_POSITION_COUNTS)):
        representatives = (0,) if ring == 0 else range(ring + 1)
        for representative in representatives:
            positions = generated_members(ring, representative)
            material = material_for_position(ring, positions[0])
            definitions.append(
                GlobalD3Orbit(
                    number=number,
                    ring=ring,
                    representative=representative,
                    material=material,
                    positions=positions,
                )
            )
            number += 1
    return tuple(definitions)


ORBITS = _build_orbits()
BY_NUMBER = {orbit.number: orbit for orbit in ORBITS}
BY_ID = {orbit.id: orbit for orbit in ORBITS}
POSITION_TO_ORBIT = {
    member: orbit.number for orbit in ORBITS for member in orbit.members
}


def orbit_for_position(ring: int, position: int) -> GlobalD3Orbit:
    """Return the global orbit containing ``(ring, position)``."""

    _validate_position(ring, position)
    return BY_NUMBER[POSITION_TO_ORBIT[(ring, position)]]


POSITION_ORDER = tuple(
    (ring, position)
    for ring, count in enumerate(RING_POSITION_COUNTS)
    for position in range(count)
)

# DRAGON/DONJON mixture ids in the declared center-then-ring position order.
# Values are stable 1-based global orbit numbers, not local-signature numbers.
MIXTURE_MAP = tuple(POSITION_TO_ORBIT[position] for position in POSITION_ORDER)


def orbit_multiplicities() -> tuple[int, ...]:
    """Return physical-position multiplicities in stable orbit-number order."""

    return tuple(orbit.multiplicity for orbit in ORBITS)


def aggregate_position_volumes(position_volumes: Iterable[float]) -> tuple[float, ...]:
    """Sum 91 physical-position volumes into the 21 global D3 orbits."""

    volumes = tuple(float(value) for value in position_volumes)
    if len(volumes) != len(POSITION_ORDER):
        raise ValueError(
            f"expected {len(POSITION_ORDER)} position volumes, found {len(volumes)}"
        )
    if any(not math.isfinite(value) or value < 0.0 for value in volumes):
        raise ValueError("position volumes must be finite and non-negative")

    totals = [0.0] * len(ORBITS)
    for orbit_number, volume in zip(MIXTURE_MAP, volumes, strict=True):
        totals[orbit_number - 1] += volume
    return tuple(totals)


def uniform_orbit_volumes(position_volume: float) -> tuple[float, ...]:
    """Return orbit volumes when every physical hexagon has equal volume."""

    value = float(position_volume)
    if not math.isfinite(value) or value < 0.0:
        raise ValueError("position volume must be finite and non-negative")
    return tuple(value * multiplicity for multiplicity in orbit_multiplicities())


if len(ORBITS) != 21 or tuple(BY_NUMBER) != tuple(range(1, 22)):
    raise RuntimeError("IRENA global D3 orbit numbering must be exactly 1..21")
if len(POSITION_TO_ORBIT) != 91 or len(MIXTURE_MAP) != 91:
    raise RuntimeError("IRENA global D3 orbit map must cover exactly 91 positions")
