"""Shared DONJON/GANLIB wire-format constants."""

LCM_CHAR_CHUNK_WIDTH = 4
LCM_DEFAULT_FLAGS = 12
LCM_BLOCK_NAME_WIDTH = 80
LCM_TEXT_LINE_WIDTH = 80
LCM_INT_FIELD_WIDTH = 10
LCM_INTS_PER_LINE = 8
LCM_REAL_FIELD_WIDTH = 16
LCM_REAL_PRECISION = 8
LCM_REALS_PER_LINE = 5
LCM_LIST_TAG_WIDTH = 8

DONJON_COMMENT_WIDTH = 80
DONJON_OBJECT_NAME_WIDTH = 72
DONJON_SIGNATURE_WIDTH = 12
DONJON_MACRO_NAME_WIDTH = 12
DONJON_ADF_NAME_WIDTH = 8
DONJON_PARAMETER_KEY_WIDTH = 12
DONJON_PARAMETER_TYPE_WIDTH = 4
DONJON_PARAMETER_FORMAT_WIDTH = 8

MGXS_DONJON_GROUP_ORDER = "mgxs_donjon"
